title: til - Bhupesh Varshney
description: Today I Learned: Interesting things I learn everyday related to software development, computer science & stuff.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

# Build settings
markdown: kramdown
kramdown:
  input: GFM
